### ISSUE TITLE
Can't build libusb-wine

### ISSUE THREAD

**Issue by cuynu** [stanson-ch/libusb-wine#2]
I cant install libusb, this is build log

`gcc -c -o linux.o linux.c -I. -I/usr/include/wine/windows -D__WINESRC__ -D_REENTRANT -g -O2 -m32 -fPIC -Wall -pipe -fno-strict-aliasing -Wempty-body -Wignored-qualifiers -Wstrict-prototypes -Wtype-limits -Wunused-but-set-parameter -Wvla -Wwrite-strings -Wpointer-arith -Wlogical-op -Wno-format-truncation -gdwarf-2 -gstrict-dwarf -fno-omit-frame-pointer
gcc -c -o error.o error.c -I. -I/usr/include/wine/windows -D__WINESRC__ -D_REENTRANT -g -O2 -m32 -fPIC -Wall -pipe -fno-strict-aliasing -Wempty-body -Wignored-qualifiers -Wstrict-prototypes -Wtype-limits -Wunused-but-set-parameter -Wvla -Wwrite-strings -Wpointer-arith -Wlogical-op -Wno-format-truncation -gdwarf-2 -gstrict-dwarf -fno-omit-frame-pointer
gcc -c -o usb.o usb.c -I. -I/usr/include/wine/windows -D__WINESRC__ -D_REENTRANT -g -O2 -m32 -fPIC -Wall -pipe -fno-strict-aliasing -Wempty-body -Wignored-qualifiers -Wstrict-prototypes -Wtype-limits -Wunused-but-set-parameter -Wvla -Wwrite-strings -Wpointer-arith -Wlogical-op -Wno-format-truncation -gdwarf-2 -gstrict-dwarf -fno-omit-frame-pointer
gcc -c -o descriptors.o descriptors.c -I. -I/usr/include/wine/windows -D__WINESRC__ -D_REENTRANT -g -O2 -m32 -fPIC -Wall -pipe -fno-strict-aliasing -Wempty-body -Wignored-qualifiers -Wstrict-prototypes -Wtype-limits -Wunused-but-set-parameter -Wvla -Wwrite-strings -Wpointer-arith -Wlogical-op -Wno-format-truncation -gdwarf-2 -gstrict-dwarf -fno-omit-frame-pointer
gcc -c -o usb-wine.o usb-wine.c -I. -I/usr/include/wine/windows -D__WINESRC__ -D_REENTRANT -g -O2 -m32 -fPIC -Wall -pipe -fno-strict-aliasing -Wempty-body -Wignored-qualifiers -Wstrict-prototypes -Wtype-limits -Wunused-but-set-parameter -Wvla -Wwrite-strings -Wpointer-arith -Wlogical-op -Wno-format-truncation -gdwarf-2 -gstrict-dwarf -fno-omit-frame-pointer
usb-wine.c:6:10: fatal error: windef.h: No such file or directory
    6 | #include <windef.h>
      |          ^~~~~~~~~~
compilation terminated.
make: *** [Makefile:38: usb-wine.o] Error 1`

**Comment by YT-Advanced** [comment]
@cuynu Ơ tưởng ai kia không xài windows thì phải đoạn tuyệt với cả win32 chứ nhỉ
À mà update lại cái title đi ông, đọc vào trông phản cảm vl. Xưa h không ai dạy ông cách đặt message cho commit với viết issues sao cho phù hợp hử
